#!/bin/busybox sh

# Default PATH differs between shells, and is not automatically exported
# by klibc dash.  Make it consistent.
export PATH=/sbin:/usr/sbin:/bin:/usr/bin

[ -d /proc ] || mkdir /proc
mount -t proc none /proc
[ -d /sys ] || mkdir /sys
mount -t sysfs none /sys

mknod /dev/null c 1 3
mknod /dev/tty c 5 0
[ -e /dev/console ] || mknod /dev/console c 5 1

mdev -s

#Hardware specific adaptions

HWDEVICE="$(cat /proc/cpuinfo | grep Hardware | awk '{print $3}' )"
if [ $HWDEVICE == ODROID-C2 ] ; then
   exec >/dev/kmsg 2>&1 </dev/console
fi

# Odroid C1, SparkySBC, Banana PI, Pine64 and Cubox have overlayfs version < V22
if [ $HWDEVICE == ODROIDC ] || [ $HWDEVICE == gs705a ] || [ $HWDEVICE == sun50iw1p1 ] || [ $HWDEVICE == sun8iw11p1 ] || [ $HWDEVICE == Freescale ]; then
   OVERLAY=NOWRKDIR
   exec >/dev/kmsg 2>&1 </dev/console
else
   OVERLAY=WITHWRKDIR
fi

echo "Booting Volumio for $(cat /proc/cpuinfo | grep Hardware )"

echo "	This script mounts rootfs RO with an overlay RW layer."
if [ $OVERLAY == WITHWRKDIR ]; then
   # For overlayfs version V22 or higher (modulename 'overlay')
   modprobe overlay
else
   # For overlayfs version V20/V21 (modulename ='overlayfs')
   modprobe overlayfs
fi
modprobe squashfs
modprobe nls_cp437

# Parse the kernel command line from grub

CMDLINE="$(cat /proc/cmdline)"

parse_disk() {
  if [ "$(echo $1|cut -c -5)" = "UUID=" ]; then
    # $1 is a UUID
    echo $(findfs $1)
  elif [ "$(echo $1|cut -c -6)" = "LABEL=" ]; then
    # $1 is a LABEL
    echo $(findfs $1)
  elif [ "$(echo $1|cut -c -5)" = "/dev/" ]; then
    # $1 is a device name
    echo $1
  else
    # $1 is unrecognized.
    echo "unknown-disk"
  fi
}

for p in ${CMDLINE};
do
  key=${p%%=*}
  value=${p#*=}
  case $key in
  imgpart)
    IMGPART=`parse_disk $value`
    ;;
  imgfile)
    IMGFILE=$value
    ;;
  bootdelay)
    BOOTDELAY=$value
    ;;
  esac
done

if [ -z "${IMGPART}" ]; then
  echo "Specify the squash image partition after the kernel command ${CMDLINE}"
  echo "example: kernel... imgpart=/dev/sda2 imgfile=/gentoo.sqs"
  exec sh
  exit 0
fi

if [ -z "${IMGFILE}" ]; then
  echo "Specify the squash image file after the kernel command ${CMDLINE}"
  echo "example: kernel... imgpart=/dev/sda2 imgfile=/gentoo.sqs"
  exec sh
  exit 0
fi

echo IMGPART=${IMGPART}
echo IMGFILE=${IMGFILE}
if [ ! -z "${BOOTDELAY}" ]; then
  echo "Boot delay (except first time) will be ${BOOTDELAY} seconds"
fi

# Retry mdev -s 3 times before throwing the towel
for i in 1 2 3 4 5 6
  do
    if [ ! -b "${IMGPART}" ]; then
      echo  "${IMGPART} not detected,retrying mdev in 5 seconds"
	  sleep 0.5
      mdev -s
    else
	  blkid ${IMGPART}
      break
    fi
  done

if [ ! -b "${IMGPART}" ]; then
  echo "No partition with ${IMGPART} has been found"
  exec sh
  exit 0
fi

# ok, parsing done
[ -d /mnt ] || mkdir /mnt
# Mount the partitions
# 1) mount the partition where the squash image resides
[ -d /mnt/imgpart ] || mkdir /mnt/imgpart
mount -t ext4 ${IMGPART} /mnt/imgpart

#create recovery image when not yet present
#when already present and a bootdelay parameter was specified then give the kernel the additional headstart
#

if [ ! -e "/mnt/imgpart/volumio_factory.sqsh" ]; then
  echo "Creating factory image, this will take a minute, please wait..."
  cp /mnt/imgpart/volumio_current.sqsh /mnt/imgpart/volumio_factory.sqsh
  echo "Factory image created"
  echo "Creating archive for factory kernel..."
  mkdir /mnt/factory
  mount -t vfat /dev/mmcblk0p1 /mnt/factory
  tar cf /mnt/imgpart/kernel_current.tar -C /mnt/factory .
  cp /mnt/imgpart/kernel_current.tar /mnt/imgpart/kernel_factory.tar
  umount /mnt/factory
  rm -r /mnt/factory

elif [ ! -z "${BOOTDELAY}" ]; then
  echo "Doing a ${BOOTDELAY} second delay here to give kernel load a headstart"
  sleep ${BOOTDELAY}
fi

#Check eventually for USB updates (could be vfat or ext4 partion --> mount auto)
echo "Check for USB updates"
[ -e /dev/sda1 ] || mdev -s
if [ -e /dev/sda1 ]; then
  [ -d /mnt/usb ] || mkdir /mnt/usb
  mount -t auto /dev/sda1 /mnt/usb
  #If there is a firmware file inside the usb
  if [ -e /mnt/usb/volumio.fir ]; then
	echo "Firmware found, updating will take a few minutes, please wait..."
    #when the partitions are mounted we can launch the update script
    volumio-init-updater
  fi
  if [ -e /mnt/usb/factory_reset ]; then
    echo "Factory Reset on USB"
    mkdir /mnt/factory
    mount -t auto /dev/mmcblk0p1 /mnt/factory
    echo " " > /mnt/factory/factory_reset
    umount /mnt/factory
    rm -r /mnt/factory
    rm /mnt/usb/factory_reset
  fi
  umount /dev/sda1
  rm -r /mnt/usb
else
  echo "No USB device detected (when incorrect, try adding 'bootdelay=5' to your boot cmdline)"
fi


# 2) init a loop pointing to the image file
loop_free=$(losetup -f | sed s#p/#p#)
losetup $loop_free /mnt/imgpart/${IMGFILE}


# 3) mount the squashfs to /mnt/static
[ -d /mnt/static ] || mkdir /mnt/static
mount -t squashfs $loop_free /mnt/static

VOLUMIO_VERSION="$(cat /mnt/static/etc/os-release | grep VOLUMIO_VERSION)"

#if there is factory file then format data partition
mkdir /mnt/factory
mount -t vfat /dev/mmcblk0p1 /mnt/factory
if [ -e "/mnt/factory/factory_reset" ]; then
  echo "Executing factory reset"
  mkfs.ext4 -F -E stride=2,stripe-width=1024 -b 4096 /dev/mmcblk0p3 -L volumio_data
  echo "Factory reset executed: part I - User DATA Part"
  tar xf /mnt/imgpart/kernel_factory.tar -C /mnt/factory
  echo "Factory reset executed: part II - Kernel"
  cp  /mnt/imgpart/volumio_factory.sqsh /mnt/imgpart/volumio_current.sqsh
  echo "Factory reset executed: part III - Squash"
  echo "Factory reset successfully executed"
  sync
  rm /mnt/factory/factory_reset

  umount /mnt/factory
  rm -r /mnt/factory
  echo "Restarting"
  reboot
fi
if [ -e "/mnt/factory/user_data" ]; then
  echo "Deleting User Data"
  mkfs.ext4 -F -E stride=2,stripe-width=1024 -b 4096 /dev/mmcblk0p3 -L volumio_data
  rm /mnt/factory/user_data
  echo "User Data successfully deleted "
fi
umount /mnt/factory
rm -r /mnt/factory

# if the update failed before completion
mkdir boot
mount -t vfat /dev/mmcblk0p1 /boot
if [ -e "/boot/update_process" ]; then
echo "Previous update attempt failed, restoring fallbacks"
  cp /mnt/imgpart/kernel_fallback.tar /mnt/imgpart/kernel_current.tar
  cp /mnt/imgpart/volumio_fallback.tar /mnt/imgpart/volumio_current.tar
  if [-e "/boot/kernel_update" ]; then
    rm /boot/kernel_update
  fi
  rm /boot/update_process
fi

# if the kernel has been updated, and no error has occurred before completition
if [ -e "/boot/kernel_update" ]; then
echo "unpacking kernel"
  tar xf /mnt/imgpart/kernel_current.tar -C /boot
  if [ -e "/mnt/imgpart/config.txt.bak" ]; then
    cp /mnt/imgpart/config.txt.bak /boot/config.txt
    rm /mnt/imgpart/config.txt.bak
  fi
  rm /boot/kernel_update
  umount /boot
  rm -rf /boot
  reboot
fi

# if data partition needs to be resized
if [ -e "/boot/resize-volumio-datapart" ]; then
echo "Re-sizing Volumio data partition"
  END="$(parted -s /dev/mmcblk0 unit MB print free | grep Free | tail -1 | awk '{print $2}' | grep -o '[0-9]\+')"
  parted -s /dev/mmcblk0 resizepart 3 ${END}
  e2fsck -fy /dev/mmcblk0p3
  resize2fs /dev/mmcblk0p3
  echo "Volumio data partition succesfully resized"
  parted -s /dev/mmcblk0 unit MB print
  rm /boot/resize-volumio-datapart
fi

# clear the mountpoint
umount /boot
rm -rf /boot

# 4) mount a filesystem for write access to the static image
# unclear: memory size? -o size=1024M
[ -d /mnt/ext ] || mkdir -m 777 /mnt/ext
mount -t ext4 -o noatime /dev/mmcblk0p3 /mnt/ext

[ -d /mnt/ext/dyn ] || mkdir -m 777 /mnt/ext/dyn
[ -d /mnt/ext/union ] || mkdir -m 777 /mnt/ext/union

# 5) mount the writable overlay to the static image
if [ $OVERLAY == WITHWRKDIR ]; then
  [ -d /mnt/ext/work ] || mkdir -m 777 /mnt/ext/work
  echo "With Option:" $OVERLAY
  mount -t overlay -olowerdir=/mnt/static,upperdir=/mnt/ext/dyn,workdir=/mnt/ext/work overlay /mnt/ext/union
else
  echo "Without Option:" $OVERLAY
  mount -t overlayfs overlayfs /mnt/ext/union -olowerdir=/mnt/static,upperdir=/mnt/ext/dyn
fi

[ -d /mnt/ext/union/static ] || mkdir -m 777 /mnt/ext/union/static
[ -d /mnt/ext/union/imgpart ] || mkdir -m 777 /mnt/ext/union/imgpart
mount --move /mnt/static /mnt/ext/union/static
mount --move /mnt/imgpart /mnt/ext/union/imgpart

chmod -R 777 /mnt/ext/union/imgpart

umount /proc
umount /sys

echo ${VOLUMIO_VERSION}
echo "Finish initramfs, continue booting Volumio"
exec switch_root /mnt/ext/union /sbin/init

echo "Failed to switch_root, dropping to a shell"
exec sh

