#!/bin/sh

set -ex

case "$2" in
in) 
    /usr/bin/logger -t netplug "Network presence event on $1"
    /sbin/ifup "$1"
    ;;
out) 
    /usr/bin/logger -t netplug "Network loss event on $1"
    /sbin/ifdown "$1"
    ;;
probe) 
    /usr/bin/logger -t netplug "Network probe on $1"
    /sbin/ifconfig "$1" up
    ;;
esac

exit 0
